In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [2]:
dataset=pd.read_csv('titanic.csv')

In [7]:
dataset # problem-is there any relationship between pclass and sex

PassengerId  Survived  Pclass         Lname  \
0              1         0       3        Braund   
1              2         1       1       Cumings   
2              3         1       3     Heikkinen   
3              4         1       1      Futrelle   
4              5         0       3         Allen   
..           ...       ...     ...           ...   
151          152         1       1         Pears   
152          153         0       3           Meo   
153          154         0       3  van Billiard   
154          155         0       3         Olsen   
155          156         0       1      Williams   

                                            Name     Sex   Age  SibSp  Parch  \
0                                Mr. Owen Harris    male  22.0      1      0   
1     Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1      0   
2                                    Miss. Laina  female  26.0      0      0   
3             Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                              Mr. William Henry    male  35.0      0      0   
..                                           ...     ...   ...    ...    ...   
151                   Mrs. Thomas (Edith Wearne)  female  22.0      1      0   
152                                  Mr. Alfonzo    male  55.5      0      0   
153                            Mr. Austin Blyler    male  40.5      0      2   
154                               Mr. Ole Martin    male   NaN      0      0   
155                            Mr. Charles Duane    male  51.0      0      1   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
1            PC 17599  71.2833   C85        C  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
..                ...      ...   ...      ...  
151            113776  66.6000    C2        S  
152        A.5. 11206   8.0500   NaN        S  
153          A/5. 851  14.5000   NaN        S  
154         Fa 265302   7.3125   NaN        S  
155          PC 17597  61.3792   NaN        C  

[156 rows x 13 columns]

In [16]:
matrix1=pd.crosstab(dataset['Pclass'],dataset['Sex'])

In [17]:
matrix1

Sex     female  male
Pclass              
1            9    21
2           12    18
3           35    61

In [21]:
object_variable=matrix1.values

In [23]:
v=stats.chi2_contingency(matrix1)

In [24]:
expected_values=v[3]

In [37]:
object_variable


array([[ 9, 21],
       [12, 18],
       [35, 61]], dtype=int64)

In [38]:
expected_values

array([[10.76923077, 19.23076923],
       [10.76923077, 19.23076923],
       [34.46153846, 61.53846154]])

In [39]:
chi2_square1=sum((o-e)**2/e for o,e in zip(object_variable,expected_values))

In [40]:
chi2_square1

array([0.43973214, 0.24625   ])

In [60]:
chi2_value=chi2_square1[0]+chi2_square1[1]

In [68]:
chi2_value

0.685982142857143

In [69]:
#########################################################################################

In [70]:
a=np.arange(6).reshape(3,2)

In [71]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
b=np.arange(6,12).reshape(3,2)

In [73]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [74]:
list(zip(a,b))

[(array([0, 1]), array([6, 7])),
 (array([2, 3]), array([8, 9])),
 (array([4, 5]), array([10, 11]))]

In [75]:
c=sum((o1-e1)**2/e1 for o1,e1 in zip(a,b))

In [76]:
c

array([14.1       , 12.41558442])

In [77]:
############################################################################3

In [82]:
help(stats.chi2.cdf)

Help on method cdf in module scipy.stats._distn_infrastructure:

cdf(x, *args, **kwds) method of scipy.stats._continuous_distns.chi2_gen instance
    Cumulative distribution function of the given RV.
    
    Parameters
    ----------
    x : array_like
        quantiles
    arg1, arg2, arg3,... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information)
    loc : array_like, optional
        location parameter (default=0)
    scale : array_like, optional
        scale parameter (default=1)
    
    Returns
    -------
    cdf : ndarray
        Cumulative distribution function evaluated at `x`



In [ ]:
################################################################################

In [95]:
no_raws=len(object_variable[:,0])
no_columns=len(object_variable[0,:])
dof=(no_raws-1)*(no_columns-1)
dof

2

In [96]:
no_raws

3

In [ ]:
#############  method1#######################

In [97]:
p_value=1-stats.chi2.cdf(chi2_value,df=dof)


In [98]:
p_value

0.709644547643955

In [100]:
if  p_value<=0.05:
    print("Null Hypothesis is rejected! There is a relationship between Pclass and Gender")
else:
    print('Null Hypothesis is accected!There is not a significant relationship between Pclass and Gender')

Null Hypothesis is accected!There is not a significant relationship between Pclass and Gender


In [101]:
help(stats.chi2.ppf)

Help on method ppf in module scipy.stats._distn_infrastructure:

ppf(q, *args, **kwds) method of scipy.stats._continuous_distns.chi2_gen instance
    Percent point function (inverse of `cdf`) at q of the given RV.
    
    Parameters
    ----------
    q : array_like
        lower tail probability
    arg1, arg2, arg3,... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information)
    loc : array_like, optional
        location parameter (default=0)
    scale : array_like, optional
        scale parameter (default=1)
    
    Returns
    -------
    x : array_like
        quantile corresponding to the lower tail probability q.



In [ ]:
##########3#######  method2 ############

In [102]:
chi2_tabulated=stats.chi2.ppf(q=1-0.05,df=dof)

In [103]:
chi2_value

0.685982142857143

In [104]:
chi2_tabulated

5.991464547107979

In [105]:
if chi2_value>=chi2_tabulated:
    print('Null Hypothesis is rejected! There is a relationship between Pclass and Gender')
else:
    print('Null Hypothesis is accected!There is not a significant relationship between Pclass and Gender')

Null Hypothesis is accected!There is not a significant relationship between Pclass and Gender
